name: Release Workflow
on: [create]

env:
  RUSTFLAGS: "-D warnings"

jobs:
  release:
    if: github.event_name == 'create' && github.event.ref_type == 'tag'
    name: Release
    runs-on: ubuntu-22.04
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install deps
        run: sudo apt-get install -y autoconf
      - name: Install configure
        run: ./configure CFLAGS="-static -O3" CC="musl-gcc" --prefix=$PWD
      - name: Build
        run: make LDFLAGS="--static -O3" && make install
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "bin/*"
          tag: ${{ github.ref }}
          name: ${{ github.ref }}
          draft: true
